name: Lint Frontend

on:
  push:
    paths:
      - 'frontend/**'

permissions:
  contents: write # Permiso necesario para que el bot haga el auto-fix

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run ESLint & Prettier (Auto-fix)
        working-directory: ./frontend
        continue-on-error: true # Solo advierte, no bloquea
        # Ejecuta la corrección automática de ESLint y luego Prettier
        run: |
          npx eslint . --fix
          npx prettier --write .

      - name: Commit Auto-fix changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style(frontend): auto-fix eslint y prettier"
